config/routes.rb
CanTeen::Application.routes.draw do
  resources :pages

  root :to => "static_pages#home"

  get "static_pages/contact_us"

  get "static_pages/about_us"

  get 'news', to: 'news#index', as: 'index_news'
  get 'news/crop', to: 'news#crop'
  resources :news

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :article_content, :article_image, :article_name, :crop_x, :crop_y, :crop_w, :crop_h

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h


  mount_uploader :article_image, ArticleImageUploader

    after_update :crop_image
  
  def crop_image
    article_image.recreate_versions! if crop_x.present?
  end

  @news_item = News.order("created_at").last

  default_scope order('created_at DESC')

end

app/models/page.rb
class Page < ActiveRecord::Base
	
  attr_accessible :parent_id, :content, :image, :name

  has_ancestry

  mount_uploader :image, MainImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  @latest_news = News.order("created_at").first
  
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news_items = News.all
    @news_item = News.new
  end


  # GET /news/new
  # GET /news/new.json
  def new
    @news_item = News.new

  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news_item = News.new(params[:news])

      if @news_item.save
        if params[:news][:article_image].present?
          render :crop
        else
           redirect_to news_index_url, notice: 'News Article was successfully created.' 
        end
      else
        render action: "index" 
      end
  end

  def crop
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news_item = News.find(params[:id])

      if @news_item.update_attributes(params[:news])
        if params[:news][:article_image].present?
          render :crop
        else
          redirect_to news_index_url, notice: 'News Article was successfully updated.' 
        end
      else
        render action: "index" 
      end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news_item = News.find(params[:id])
    @news_item.destroy
    redirect_to news_index_url, notice: 'News Article was destroyed' 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@news_item = News.order("created_at").first
  end

  def contact_us
  end

  def about_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer"></div>

app/views/layouts/_left_hand_column.html.erb
<div id="col1" class="column">	
	<% if params[:controller] == 'pages' && params[:action] == "show"%>
			<h4><%= @page.root.name %></h4>
		<div id="sub_nav">
  			<%= render 'layouts/submenu_pages', pages: @page.root.descendants.arrange %>
		</div>
	<% else %>
		<h4> Second Navigation</h4>	
	<% end %>
</div>

app/views/layouts/_main_nav.html.erb
    <div id="super_nav">
        <div id="nav">
            <ul>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "News", :controller => "news", :action => "index" %></li>
                <% unless (params[:controller] == "pages" && params[:action] != "index") %>
                <% Page.roots.each do |page| %>
                <li><%= link_to page.name, page %></li>
                <% end %>
                <% end %>
                <li><a href="#" class="no_border">Contact</a></li>
            </ul> 
        </div>
    		<div id="overlay"></div>
    </div>

app/views/layouts/_right_hand_column.html.erb
<div id="col3">
	<div id="latest_news">
		 <h3>Latest News</h3>
	 <% news_item = News.order("created_at").first %>
    <% if news_item.present? %>
     <div class="title">
        <h4><%= news_item.article_name %></h4>
        <span><%= (news_item.created_at).strftime("Posted  on %m/%d/%Y") %></span>
    </div>
       <%# if news_item.article_image? %>
       	<%#= image_tag news_item.article_image_url(:thumb).to_s, :width => 150 %>
       <%# end%>
        <div style="clear:both"></div>
        <p><%= news_item.article_content%></p>
     <% else %>
        <strong><p>No news today</p></strong>
     <% end %>



</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CanTeen</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<div id="header">
<a href="/" class="logo">Canteen Ireland</a>

		<ul id="networks" style="margin-top:0px">
			<li><a href="#" class="linkedin" rel="external">LinkedIn</a></li>		
			<li><a href="http://www.youtube.com/user/CanTeenIreland1" class="youtube" rel="external">Youtube</a></li>
			<li><a href="https://twitter.com/CanTeen_Ireland" class="twitter" rel="external">Twitter</a></li>
			<li><a href="https://www.facebook.com/CanTeenIreland" class="facebook" rel="external">Facebook</a></li>
		</ul>

</div> <!-- header -->


	<%= render "layouts/main_nav"%>


	 <div id="master">
      <div id="page">
        <div class="wrapper">
          <div class="spacer">


			<%# unless params[:action] == 'home'%>
			<%= render "layouts/left_hand_column"%>
			<%# end %>
			<%= yield %>
			<%= render "layouts/right_hand_column"%>
			 <div style="clear:both"></div>
			<%= render "layouts/footer"%>
          </div><!-- spacer -->
         
        </div>
        <!-- /wrapper -->
       
      </div>
       <span class="foot-holder"></span>
      <!-- /page -->
    </div>
    <!-- /master -->
		
</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_name %><br />
    <%= f.text_field :article_name %>
  </div>
  <div class="field">
    <%= f.label :article_content %><br />
    <%= f.text_field :article_content %>
  </div>
  <div class="field">
    <%= f.label :article_image %><br />
    <%= f.text_field :article_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/crop.html.erb
<div id="col2" class="column">
<h1>Crop Image</h1>
<%=image_tag  @news_item.article_image_url(:large).to_s, :id => "cropbox" %>

<h4>Preview</h4>
<div style="width:150px; height:100px; overflow:hidden">
  <%= image_tag @news_item.article_image_url(:large), :id => "preview" %>
</div>


<%= form_for @news_item do |f| %>
	<% %w[x y w h].each do |attribute| %>
		<%= f.text_field  "crop_#{attribute}", :id => "crop_#{attribute}" %>
	<% end %>
	<%= f.submit "Crop" %>
<% end %>



  <div class="actions">
    <%# %w[x y w h].each do |attribute| %>
      <%#= f.text_field "crop_#{attribute}"%>
    <%# end %>
    
  </div>
<%# end %>
</div>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<div id="col2" class="column">

 <% content_for :title, "Community News" %>

  <%# if admin_user %>
  

<fieldset>
    <%= form_for @news_item, :html =>  {:class => "form-horizontal", :multipart => true } do |f| %>
        <% if @news_item.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize( @news_item.errors.count, "error") %> prohibited this news from being saved:</h2>

            <ul>
            <%  @news_item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

      <div class="control-group">
        
        <strong><h3>Enter News Article</h3></strong>
        
        <%= f.label :article_name, "Article Title", class: "control-label" %>
            <div class="controls">
        <%= f.text_field :article_name, class: "input-xlarge" %></div></div>
           <div class="control-group">
        
        <%= f.label :article_content, "Content", class: "control-label" %>
            <div class="controls">
        <%= f.text_area :article_content, :rows => '7', class: "input-xlarge" %></div></div>
        
        <%= f.label :article_image, "Image", class: "control-label" %>
            <div class="controls">
        <%= f.file_field :article_image, class: "input-xlarge" %></div>
          <br/>
            <div class="control-group"> <div class="controls">
        <%= f.submit "Submit", class: "btn btn-primary btn-large" %> </div></div>

    <% end %>
  </fieldset>
  <br/>


<div id="news_items">
   <h3>Latest News</h3>
  <ul>
    <% @news_items.each do |news_item|%>
    <% if news_item.present? %>
      <div class="title">
        <h4><%= news_item.article_name %></h4>
        <span><%= (news_item.created_at).strftime("Posted  on %m/%d/%Y") %></span><br/>
    </div>
        <% if news_item.article_image? %>
        <%= image_tag news_item.article_image_url(:thumb).to_s, :width => 250 %>
        <%end%>
        <div style="clear:both"></div>
        <p><%= news_item.article_content%></p>
        <%= button_to 'Destroy', news_item, method: :delete, data: { confirm: 'Are you sure?' } %>
     <br/>
     <hr/>
     <% else %>
        <strong><p>No news today</p></strong>
     <% end %>
   <% end %>
 </ul>
</div>

</div>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article name:</b>
  <%= @news.article_name %>
</p>

<p>
  <b>Article content:</b>
  <%= @news.article_content %>
</p>

<p>
  <b>Article image:</b>
  <%= @news.article_image %>
</p>


<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/pages/_form.html.erb
<%= form_for @page,:html => {:multipart => true} do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <%= f.label :parent_id, "Parent ID" %><br />
  <%= f.collection_select :parent_id, Page.order(:name), :id, :name, include_blank: true %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div id="col2">
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Ansetry', pages_path %>
</div>

app/views/pages/index.html.erb
<div id="col2">
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Content</th>
    <th>Ancestry</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= page.image %></td>
    <td><%= page.content %></td>
    <td><%= page.ancestry %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>
</div>

app/views/pages/new.html.erb
<div id="col2">
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>
</div>

app/views/pages/show.html.erb
<div id="col2">
<p id="notice"><%= notice %></p>


  


 <div class="main_image">
	<%= image_tag @page.image_url, :width => 450 %>
</div>

<h1><%= @page.name %></h1>



  <%= @page.content.html_safe %>


<p>
  <b>Ancestry:</b>
  <%= @page.ancestry %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>
</div>

app/views/static_pages/about_us.html.erb
<h1>StaticPages#about_us</h1>
<p>Find me in app/views/static_pages/about_us.html.erb</p>

app/views/static_pages/contact_us.html.erb
<h1>StaticPages#contact_us</h1>
<p>Find me in app/views/static_pages/contact_us.html.erb</p>

app/views/static_pages/home.html.erb
<div id="col2" class="column">

<div class="slider"> 
	<%= image_tag "alton_towers.jpg", :alt => "alton towers", :height => 270%> 
	<%= image_tag "baratstown.jpg", :alt =>"baratstown", :height => 270 %> 
	<%= image_tag "celebs.jpg", :alt => "celeberaty patrons", :height=> 270 %> 
	<%= image_tag "fire_brigade.jpg", :alt => "dublin city fire brigade", :height => 270 %>
</div>
<br>
<div id="news_items">
	 <h3>Latest News</h3>
	 <br/>
    <% if @news_item.present? %>
     <div class="title">
        <h4><%= @news_item.article_name %></h4><br/>
        <span><%= (@news_item.created_at).strftime("Posted  on %m/%d/%Y") %></span><br/>
    </div>
       <% if @news_item.article_image? %>
       	<%= image_tag @news_item.article_image_url(:thumb).to_s, :width => 150 %>
       <%end%>
        <div style="clear:both"></div>
        <p><%= @news_item.article_content%></p>
     <% else %>
        <strong><p>No news today</p></strong>
     <% end %>
</div>

	<input type="button" onclick="myFunction()" value="Show alert box">
  <%= button_to "Page Index", pages_path, :method => "get" %>

</div>